src/Views/Prescription.js

Visual when no files
Visual when file loaded

Prescription visual upload

---

src/Components/Landing/LandingPage.js
src/Components/Landing/NavbarLanding/NavbarLanding.js
src/Components/Landing/Parallax/Parallax.js
src/Components/Landing/Parallax/PreviewSection.js

- Update landing page features to the new vision.
- Add "carte" button which redirects to /map

Update landing features

---

src/Components/Login/Login.js
src/Components/Shared/Api/api.js

Fix login issue due to site migration

[FIX] Auth #43

---

config/webpack.config.prod.js
src/Components/Landing/Parallax/ContactForm.js
src/Components/Landing/Parallax/ContactForm.scss
src/Components/Landing/Parallax/Parallax.js
src/Components/Landing/Parallax/Parallax.scss
src/Components/Login/Login.js
src/Components/Map/Map.js
src/Components/Map/Map.scss
src/Components/Map/MapRouting.js
src/Components/Map/Shared/LocateUser.js
src/Components/Map/Shared/Search.js
src/Components/Map/Shared/Slider.js

* Lorsque des urgences sont sélectionnées, affichage de l'itinéraire jusqu'à ces urgences
* Réglage de l'affichage des urgences en fonction du rayon fonctionnel
* Correction du bug lorsqu'on active la géolocalisation
* Réinitialisation de l'itinéraire lorsqu'on rentre une nouvelle adresse

Affichage itinéraire avec hôpitaux et cliniques à proximité

---

src/Components/Map/Map.js
src/Components/Map/MapRouting.js

(en utilisant un hôpital à proximité)

Réinitialisation de l'itinéraire après MAJ addresse

---

src/Components/Map/Map.js
src/Components/Map/MapRouting.js

Revert "Réinitialisation de l'itinéraire après MAJ addresse"

---

src/Components/Landing/NavbarLanding/Styles.scss

Fix navbar button style

---

src/Components/Chat/Api.js
src/Components/Shared/Api/api.js

Change the API endpoints to the public one instead of localhost

[fix] api public endpoints

---

src/Components/Profile/Profile.js
src/Components/Profile/Profile.scss
src/Components/Settings/Settings.js

Jean-Baptiste Melet's commit, rebased by me

[dev minor] changed /Profile design (JB Melet)

---

public/index.html
src/Components/Map/Map.js
src/Components/Map/Map.scss
src/Components/Map/Shared/RequestUberPopup.js

Lorsqu'on sélectionne un hôpital, un bouton supplémentaire apparaît à côté des modes de transport. Ce bouton ouvre un popup qui demande si on veut faire appel à un Uber pour aller jusqu'à l'hôpital. Si l'utilisateur accepte, la webapp Uber est ouverte avec le trajet pré-rempli.
Pas d'estimation du temps d'attente ni du prix dans le popup pour l'instant (requiert une autorisation spéciale d'Uber).

Appel d'un UBER depuis la carte

---

src/Components/Chat/ChatBotWidget.js

[fix] typo

---

src/Components/Map/Map.js
src/Components/Map/Map.scss
src/Components/Map/Shared/PopupDialog.scss
src/Components/Map/Shared/RequestUberPopup.js

- fixed slider refresh bug
- fixed nearest hospital refresh bug when using geolocation
- fixed hospital info window bug
- fixed route refresh on slider value change bug (destination could be an hospital no longer on the map)
- fixed unwanted crazy zoom when clicking anywhere
- fixed route additional waypoints bug
- improved uber ride popup CSS

[fix] bugfixes

---

src/Components/Landing/Components/ContactForm.js

Change email validation method + moved nodemailer to backend

---

src/Components/Landing/Components/Navbar.js
src/Components/Landing/Components/PreviewSection.js

Navbar update + mise à jour du texte sur la landing à propos de la création de compte sur le mobile

Navbar update + changement de texte sur la landing

---

src/Components/Landing/Components/ContactForm.js

Removed Facebook and Twitter buttons

Removed useless buttons

---

src/Components/Chat/Api.js

Changed "customer message" to "message"

Fix customer message in Chat api

---

src/Components/Landing/Components/Navbar.js

Navbar : renamed Chatbot into Chat en ligne

---

src/Components/Chat/ChatBotWidget.js

Renamec chatbot into chat en ligne

Renamed chatbot into chat en ligne

---

data/nginx/app.conf

Nginx removed access logs

---

docker-compose.yml

Disabled docker log (RGPD)

---

src/Translations/en.json

[FIX] Fixed small typo

---

src/Components/Chat/ChatBotWidget.scss

Fixed the [mobile screen and chat issue](https://github.com/Wolox/react-chat-widget/issues/21) by using [this](https://github.com/Wolox/react-chat-widget/issues/211)

[FIX] Mobile screen and chat issue

---

src/Components/Chat/ChatBotWidget.js
src/Components/Landing/Components/ContactForm.js

[fix] badgeCount now reset when component mounted

---

src/Components/Map/Map.js
src/Components/Map/Map.scss
src/Components/Map/Shared/ResultTypes.js
src/Translations/en.json
src/Translations/fr.json

- checkboxes for result types
- tooltips (with translations) on action buttons
- bugfix (duplicate keys issue)

Checkboxes for result types + bugfixes
